// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getConnectivityMode } from "@/data/connectivityMode";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const offlineFetch: typeof fetch = (input, init) => {
  const isManualOffline = getConnectivityMode() === "offline";
  const isNetworkOffline = typeof navigator !== "undefined" && !navigator.onLine;
  if (isManualOffline || isNetworkOffline) {
    return Promise.resolve(
      new Response(JSON.stringify({ message: "Offline mode enabled" }), {
        status: 503,
        headers: { "Content-Type": "application/json" },
      })
    );
  }
  return fetch(input, init);
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: offlineFetch,
  },
});